stages:
  - build
  - test
build-tv:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker pull registry.gitlab.com/kirrupt/kirrupt-tv-elixir/tv:latest || true
    - docker build -t registry.gitlab.com/kirrupt/kirrupt-tv-elixir/tv:$CI_COMMIT_SHA ./tv/
    - docker push registry.gitlab.com/kirrupt/kirrupt-tv-elixir/tv:$CI_COMMIT_SHA
    - docker tag registry.gitlab.com/kirrupt/kirrupt-tv-elixir/tv:$CI_COMMIT_SHA registry.gitlab.com/kirrupt/kirrupt-tv-elixir/tv:latest
    - docker push registry.gitlab.com/kirrupt/kirrupt-tv-elixir/tv:latest
build-auth:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker pull registry.gitlab.com/kirrupt/kirrupt-tv-elixir/auth:latest || true
    - docker build -t registry.gitlab.com/kirrupt/kirrupt-tv-elixir/auth:$CI_COMMIT_SHA ./auth/
    - docker push registry.gitlab.com/kirrupt/kirrupt-tv-elixir/auth:$CI_COMMIT_SHA
    - docker tag registry.gitlab.com/kirrupt/kirrupt-tv-elixir/auth:$CI_COMMIT_SHA registry.gitlab.com/kirrupt/kirrupt-tv-elixir/auth:latest
    - docker push registry.gitlab.com/kirrupt/kirrupt-tv-elixir/auth:latest
build-recommendation:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker pull registry.gitlab.com/kirrupt/kirrupt-tv-elixir/recommendation:latest || true
    - docker build -t registry.gitlab.com/kirrupt/kirrupt-tv-elixir/recommendation:$CI_COMMIT_SHA ./recommendation/
    - docker push registry.gitlab.com/kirrupt/kirrupt-tv-elixir/recommendation:$CI_COMMIT_SHA
    - docker tag registry.gitlab.com/kirrupt/kirrupt-tv-elixir/recommendation:$CI_COMMIT_SHA registry.gitlab.com/kirrupt/kirrupt-tv-elixir/recommendation:latest
    - docker push registry.gitlab.com/kirrupt/kirrupt-tv-elixir/recommendation:latest
build-images:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker pull registry.gitlab.com/kirrupt/kirrupt-tv-elixir/images:latest || true
    - docker build -t registry.gitlab.com/kirrupt/kirrupt-tv-elixir/images:$CI_COMMIT_SHA ./images/
    - docker push registry.gitlab.com/kirrupt/kirrupt-tv-elixir/images:$CI_COMMIT_SHA
    - docker tag registry.gitlab.com/kirrupt/kirrupt-tv-elixir/images:$CI_COMMIT_SHA registry.gitlab.com/kirrupt/kirrupt-tv-elixir/images:latest
    - docker push registry.gitlab.com/kirrupt/kirrupt-tv-elixir/images:latest
test:
  image: quay.io/aspenmesh/minikube-dind
  stage: test
  script:
    - /start.sh &
    - sleep 30
    - kubectl get nodes || true
    - docker ps
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker pull registry.gitlab.com/kirrupt/kirrupt-tv-elixir/tv:$CI_COMMIT_SHA
    - docker tag registry.gitlab.com/kirrupt/kirrupt-tv-elixir/tv:$CI_COMMIT_SHA registry.gitlab.com/kirrupt/kirrupt-tv-elixir/tv:$CI_COMMIT_SHORT_SHA
    - docker pull registry.gitlab.com/kirrupt/kirrupt-tv-elixir/auth:$CI_COMMIT_SHA
    - docker tag registry.gitlab.com/kirrupt/kirrupt-tv-elixir/auth:$CI_COMMIT_SHA registry.gitlab.com/kirrupt/kirrupt-tv-elixir/auth:$CI_COMMIT_SHORT_SHA
    - docker pull registry.gitlab.com/kirrupt/kirrupt-tv-elixir/recommendation:$CI_COMMIT_SHA
    - docker tag registry.gitlab.com/kirrupt/kirrupt-tv-elixir/recommendation:$CI_COMMIT_SHA registry.gitlab.com/kirrupt/kirrupt-tv-elixir/recommendation:$CI_COMMIT_SHORT_SHA
    - docker pull registry.gitlab.com/kirrupt/kirrupt-tv-elixir/images:$CI_COMMIT_SHA
    - docker tag registry.gitlab.com/kirrupt/kirrupt-tv-elixir/images:$CI_COMMIT_SHA registry.gitlab.com/kirrupt/kirrupt-tv-elixir/images:$CI_COMMIT_SHORT_SHA
    - curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v0.25.0/skaffold-linux-amd64 && chmod +x skaffold && sudo mv skaffold /usr/local/bin
    - skaffold run
    - sudo kubectl port-forward service/ambassador 80 &
    - make cypress-ci
