stages:
  - build
  - test
  - deploy
build-tv:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker pull registry.gitlab.com/kirrupt/kirrupt-tv-elixir/tv:latest || true
    - docker build --cache-from registry.gitlab.com/kirrupt/kirrupt-tv-elixir/tv:latest -t registry.gitlab.com/kirrupt/kirrupt-tv-elixir/tv:$CI_COMMIT_SHA ./tv/
    - docker push registry.gitlab.com/kirrupt/kirrupt-tv-elixir/tv:$CI_COMMIT_SHA
    - docker tag registry.gitlab.com/kirrupt/kirrupt-tv-elixir/tv:$CI_COMMIT_SHA registry.gitlab.com/kirrupt/kirrupt-tv-elixir/tv:latest
    - docker push registry.gitlab.com/kirrupt/kirrupt-tv-elixir/tv:latest
build-e2e:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker pull registry.gitlab.com/kirrupt/kirrupt-tv-elixir/ci-cypress:latest || true
    - docker build --cache-from registry.gitlab.com/kirrupt/kirrupt-tv-elixir/ci-cypress:latest -t registry.gitlab.com/kirrupt/kirrupt-tv-elixir/ci-cypress:$CI_COMMIT_SHA ./ci/cypress/
    - docker push registry.gitlab.com/kirrupt/kirrupt-tv-elixir/ci-cypress:$CI_COMMIT_SHA
    - docker tag registry.gitlab.com/kirrupt/kirrupt-tv-elixir/ci-cypress:$CI_COMMIT_SHA registry.gitlab.com/kirrupt/kirrupt-tv-elixir/ci-cypress:latest
    - docker push registry.gitlab.com/kirrupt/kirrupt-tv-elixir/ci-cypress:latest

test-e2e:
  image: registry.gitlab.com/kirrupt/kirrupt-tv-elixir/ci-cypress:$CI_COMMIT_SHA
  services:
    - docker:dind
  stage: test
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker-compose up -d
    - retry --verbose -i 5s -c 200 make check-db
    - retry --verbose -i 5s -c 200 curl --fail --show-error http://localhost:8080/account/login
    - make cypress-ci

deploy-staging:
  image: registry.gitlab.com/kirrupt/kirrupt-tv-elixir/ci-cypress:$CI_COMMIT_SHA
  stage: deploy
  only:
    - staging
  script:
    - mkdir -p ~/.kube
    - echo "$KUBE_STAGING_KUBECONFIG" > ~/.kube/config
    - kubectl delete secret gitlab-auth || true
    - kubectl create secret docker-registry gitlab-auth --docker-server=registry.gitlab.com --docker-password=$CI_JOB_TOKEN --docker-username=gitlab-ci-token
    - skaffold deploy --images registry.gitlab.com/kirrupt/kirrupt-tv-elixir/tv:$CI_COMMIT_SHA -p staging
