version: '3.1'
services:
  mariadb:
    image: mariadb
    restart: always
    ports:
      - "0.0.0.0:3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
  dev:
    build: ./
    ports:
      - "0.0.0.0:8080:8080"
    restart: always
    volumes:
      - ./data/shows/:/app/shows
      - ./lib:/app/lib
      - ./web:/app/web
      - ./test:/app/test
      - ./config:/app/config
    environment:
      - MIX_ENV=dev
      - MYSQL_HOST=mariadb
  prod:
    build: ./
    ports:
      - "0.0.0.0:8080:8080"
    restart: always
    environment:
      - PORT=8080
      - MYSQL_HOST=mariadb
  test:
    build: ./
    environment:
      - MIX_ENV=test
      - MYSQL_HOST=mariadb
    command: exit 0
  cypress:
    image: cypress/included:4.4.0
    entrypoint: ['bash', '-c', 'exit 0']
    volumes:
      - ./e2e/cypress:/cypress
      - ./e2e/cypress.json:/cypress.json
