version: '3.1'
services:
  mariadb:
    image: mariadb
    ports:
      - "0.0.0.0:3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
  tv:
    build: ./tv/
    ports:
      - "0.0.0.0:8080:8080"
    restart: always
    volumes:
      - ./data/shows/:/app/shows
      - ./tv/lib:/app/lib
      - ./tv/web:/app/web
      - ./tv/test:/app/test
      - ./tv/config:/app/config
    environment:
      - PORT=8080
      - MIX_ENV=dev
      - MYSQL_HOST=mariadb
      - MYSQL_USER=root
      - MYSQL_PASS=password
      - MYSQL_DB=kirrupt
      - SENTRY_DSN=
    command: mix phx.server
  test:
    build: ./tv/
    volumes:
      - ./data/shows/:/app/shows
      - ./tv/lib:/app/lib
      - ./tv/web:/app/web
      - ./tv/test:/app/test
      - ./tv/config:/app/config
    environment:
      - PORT=8080
      - MIX_ENV=dev
      - MYSQL_HOST=mariadb
      - MYSQL_USER=root
      - MYSQL_PASS=password
      - MYSQL_DB=kirrupt_test
      - SENTRY_DSN=
    command: exit 0
  cypress:
    image: cypress/included:4.4.0
    entrypoint: ['bash', '-c', 'exit 0']
    volumes:
      - ./tests/e2e/cypress:/cypress
      - ./tests/e2e/cypress.json:/cypress.json
