version: '3.1'
services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
  tv:
    build: ./tv/
    ports:
      - "0.0.0.0:8080:8080"
    restart: always
    volumes:
      - ./data/shows/:/app/shows
    environment:
      - PORT=8080
      - MIX_ENV=dev
      - MYSQL_HOST=mariadb
      - MYSQL_USER=root
      - MYSQL_PASS=password
      - MYSQL_DB=kirrupt
      - SENTRY_DSN=
    command: mix phoenix.server
  cypress:
    image: cypress/included:4.4.0
    entrypoint: exit 0
    volumes:
      - ./tests/integration/cypress:/cypress
      - ./tests/integration/cypress.json:/cypress.json
