apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: registry.gitlab.com/kirrupt/kirrupt-tv-elixir/tv
    workspace: ./tv/

deploy:
  kubectl:
    manifests:
    - ./tv/kubernetes/*
    - ./mariadb/kubernetes/*
    - ./ambassador/kubernetes/*

profiles:
- name: staging
  deploy:
    kubectl:
      manifests:
        - ./tv/kubernetes/*
        - ./mariadb/kubernetes/*
