apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
  - image: registry.gitlab.com/kirrupt/kirrupt-tv-elixir/tv
    context: ./tv/

deploy:
  kubectl:
    manifests:
    - ./tv/kubernetes/*
    - ./mariadb/kubernetes/*
    - ./ambassador/kubernetes/*

profiles:
- name: staging
  deploy:
    kubectl:
      manifests:
        - ./tv/kubernetes/*
        - ./mariadb/kubernetes/*
