apiVersion: v1
kind: Service
metadata:
  name: auth
  labels:
    app: auth
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  auth-mapping
      prefix: /api/v3/auth/
      service: auth:8080
      ---
      apiVersion: ambassador/v0
      kind:  AuthService
      name:  authentication
      auth_service: "auth:8080"
      path_prefix: "/extauth"
      allowed_headers:
      - "x-user"
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: auth
  selector:
    app: auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: registry.gitlab.com/kirrupt/kirrupt-tv-elixir/auth
        ports:
        - containerPort: 8081
        env:
        - name: MYSQL_HOST
          value: "mariadb"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASS
          value: "test"
        - name: MYSQL_DB
          value: "kirrupt"
