apiVersion: v1
kind: Service
metadata:
  name: images
  labels:
    app: images
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  images-mapping
      prefix: /shows/
      service: images:8080
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: images
  selector:
    app: images
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: images
  labels:
    app: images
spec:
  replicas: 1
  selector:
    matchLabels:
      app: images
  template:
    metadata:
      labels:
        app: images
    spec:
      containers:
      - name: images
        image: registry.gitlab.com/kirrupt/kirrupt-tv-elixir/images
        ports:
        - containerPort: 8080
