apiVersion: v1
kind: Service
metadata:
  name: tv
  labels:
    app: tv
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  tv-mapping
      prefix: /
      service: tv:8080
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: tv
  selector:
    app: tv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tv
  labels:
    app: tv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tv
  template:
    metadata:
      labels:
        app: tv
    spec:
      containers:
      - name: tv
        image: registry.gitlab.com/kirrupt/kirrupt-tv-elixir/tv
        command: ['mix', 'phoenix.server']
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: MIX_ENV
          value: "dev"
        - name: MYSQL_HOST
          value: "mariadb"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASS
          value: "test"
        - name: MYSQL_DB
          value: "kirrupt"
