#!/usr/bin/env python3

services = [
  'tv',
  'auth',
  'recommendation',
  'images',
]

dev_services = [
  'mariadb',
  'ambassador'
]

with open('skaffold.yaml', 'w') as f:
  f.write("""apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:""")

  for s in services:
    f.write("""
  - imageName: registry.gitlab.com/kirrupt/kirrupt-tv-elixir/{name}
    workspace: ./{name}/
""".format(name=s))
  
  f.write("""
deploy:
  kubectl:
    manifests:
""")

  for s in services + dev_services:
      f.write("""    - ./{name}/kubernetes/*
""".format(name=s))

with open('.gitlab-ci.yml', 'w') as f:
  f.write("""stages:
  - build
  - test
""")

  for s in services:
    f.write("""build-{name}:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker pull registry.gitlab.com/kirrupt/kirrupt-tv-elixir/{name}:latest || true
    - docker build -t registry.gitlab.com/kirrupt/kirrupt-tv-elixir/{name}:$CI_COMMIT_SHA ./{name}/
    - docker push registry.gitlab.com/kirrupt/kirrupt-tv-elixir/{name}:$CI_COMMIT_SHA
    - docker tag registry.gitlab.com/kirrupt/kirrupt-tv-elixir/{name}:$CI_COMMIT_SHA registry.gitlab.com/kirrupt/kirrupt-tv-elixir/{name}:latest
    - docker push registry.gitlab.com/kirrupt/kirrupt-tv-elixir/{name}:latest
""".format(
      name=s
    ))

  f.write("""test:
  image: quay.io/aspenmesh/minikube-dind
  stage: test
  script:
    - /start.sh &
    - sleep 30
    - kubectl get nodes || true
    - docker ps
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
""")

  for s in services:
    f.write("""    - docker pull registry.gitlab.com/kirrupt/kirrupt-tv-elixir/{name}:$CI_COMMIT_SHA
    - docker tag registry.gitlab.com/kirrupt/kirrupt-tv-elixir/{name}:$CI_COMMIT_SHA registry.gitlab.com/kirrupt/kirrupt-tv-elixir/{name}:$CI_COMMIT_SHORT_SHA
""".format(
      name=s
    ))

  f.write("""    - curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v0.25.0/skaffold-linux-amd64 && chmod +x skaffold && sudo mv skaffold /usr/local/bin
    - skaffold run
    - sudo kubectl port-forward service/ambassador 80 &
    - make cypress-ci
""")
