apiVersion: v1
kind: Service
metadata:
  name: recommendation
  labels:
    app: recommendation
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  recommendation-mapping
      prefix: /api/v1/recommendation/
      service: recommendation:8080
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: recommendation
  selector:
    app: recommendation
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation
  labels:
    app: recommendation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation
  template:
    metadata:
      labels:
        app: recommendation
    spec:
      containers:
      - name: recommendation
        image: registry.gitlab.com/kirrupt/kirrupt-tv-elixir/recommendation
        ports:
        - containerPort: 8081
