name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install retry
        run: curl -sLo linux_amd64.zip https://github.com/linyows/go-retry/releases/download/v0.3.1/linux_amd64.zip && unzip linux_amd64.zip && sudo mv retry /usr/local/bin
      
      - uses: whoan/docker-build-with-cache-action@v5
        with:
          username: kirrupt
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: docker.pkg.github.com
          image_name: kirrupt-tv
          context: ./
          dockerfile: Dockerfile

      - name: Update `docker-compose.yml`
        run: 'sed -i -e "s+build: ./+image: $IMAGE_SHA_NAME+g" docker-compose.yml'
        env:
          IMAGE_SHA_NAME: ${{ steps.docker.outputs.IMAGE_SHA_NAME }}

      - name: Check formatting
        run: docker-compose run test mix format --check-formatted

      - name: Run DB
        run: docker-compose up -d mariadb
      - name: Wait for DB
        run: retry --verbose -i 5s -c 20 make check-db
      - name: Seed DB
        run: make seed
      - name: Unit & integration tests
        run: docker-compose run -T test mix coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run web server
        run: docker-compose up -d prod
      - name: Test E2E
        uses: cypress-io/github-action@v2
        with:
          working-directory: e2e/
          wait-on: 'http://localhost:8080/'
          # wait for 2 minutes for the server to respond
          wait-on-timeout: 120
      # after the test run completes
      # store videos and any screenshots
      # NOTE: screenshots will be generated only if E2E test failed
      # thus we store screenshots only on failures
      # Alternative: create and commit an empty cypress/screenshots folder
      # to always have something to upload
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: e2e/cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      #- uses: actions/upload-artifact@v2
      #  if: always()
      #  with:
      #    name: cypress-videos
      #    path: e2e/cypress/videos
      - name: Debug logs
        if: always()
        run: docker-compose logs
  deploy:
    needs: [test]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: run webhook
        run: curl -X POST --silent --show-error --fail $webhook
        env:
          webhook: ${{ secrets.WEBHOOK }}
