name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install retry
        run: curl -sLo linux_amd64.zip https://github.com/linyows/go-retry/releases/download/v0.3.1/linux_amd64.zip && unzip linux_amd64.zip && sudo mv retry /usr/local/bin
      - name: Build and publish
        uses: machine-learning-apps/gpr-docker-publish@master
        id: docker
        with:
          CACHE: true
          IMAGE_NAME: 'kirrupt-tv'
          DOCKERFILE_PATH: './tv/Dockerfile'
          BUILD_CONTEXT: './tv'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update `docker-compose.yml`
        run: 'sed -i -e "s+build: ./tv/+image: $IMAGE_SHA_NAME+g" docker-compose.yml'
        env:
          IMAGE_SHA_NAME: ${{ steps.docker.outputs.IMAGE_SHA_NAME }}
      - name: Run DB
        run: docker-compose up -d mariadb
      - name: Wait for DB
        run: retry --verbose -i 5s -c 20 make check-db
      - name: Run web server
        run: docker-compose up -d tv
      - name: Wait for web server
        run: retry --verbose -i 5s -c 30 curl --fail --show-error http://localhost:8080/
      - name: Test
        run: make cypress-ci
      - name: Debug logs
        if: always()
        run: docker-compose logs
