name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install retry
        run: curl -sLo linux_amd64.zip https://github.com/linyows/go-retry/releases/download/v0.3.1/linux_amd64.zip && unzip linux_amd64.zip && sudo mv retry /usr/local/bin
      - name: Build and publish
        uses: machine-learning-apps/gpr-docker-publish@master
        id: docker
        with:
          CACHE: true
          IMAGE_NAME: 'kirrupt-tv'
          DOCKERFILE_PATH: './tv/Dockerfile'
          BUILD_CONTEXT: './tv'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update `docker-compose.yml`
        run: 'sed -i -e "s+build: ./tv/+image: $IMAGE_SHA_NAME+g" docker-compose.yml'
        env:
          IMAGE_SHA_NAME: ${{ steps.docker.outputs.IMAGE_SHA_NAME }}
      - name: Run DB
        run: docker-compose up -d mariadb
      - name: Wait for DB
        run: retry --verbose -i 5s -c 20 make check-db
      - name: Unit & integration tests
        run: make test
      - name: Seed database
        run: make seed
      - name: Run web server
        run: docker-compose up -d tv
      - name: Test E2E
        uses: cypress-io/github-action@v1
        with:
          working-directory: tests/e2e/
          wait-on: 'http://localhost:8080/'
          # wait for 2 minutes for the server to respond
          wait-on-timeout: 120
      # after the test run completes
      # store videos and any screenshots
      # NOTE: screenshots will be generated only if E2E test failed
      # thus we store screenshots only on failures
      # Alternative: create and commit an empty cypress/screenshots folder
      # to always have something to upload
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: tests/e2e/cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: tests/e2e/cypress/videos
      - name: Debug logs
        if: always()
        run: docker-compose logs
